resolver: lts-7.19
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
           url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
           sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9

packages:
- .
- ../common
- location:
    git: https://github.com/ariep/plug.git
    commit: aa8e4c6e38aef843e3f7ea2e3962858da618a6e8
  subdirs:
    - plug-common
    - plug-client
  extra-dep: true
- location:
    git: https://github.com/ariep/Coroutine.git
    commit: 19939a1bf73af951e06931fd29eacd45f5761ca8
  extra-dep: true
- location:
    git: https://github.com/ariep/ID.git
    commit: 489623f74274dd360519726ea3358a65f5dfa811
  extra-dep: true
- location:
    git: https://github.com/ariep/text-index.git
    commit: 8f4453c088a786af89ef4a6079476d58add9b1ed
  extra-dep: true
- location:
    git: https://github.com/ariep/language-spelling.git
    commit: 98936c01f0fc0baf35b24e9ae975a5d808123aa3
  subdirs: [tst]
  extra-dep: true
- location:
    git: https://github.com/ariep/psqueues.git
    commit: 1b9d87511bce9f5a3e4db6fa46a43dc03a965308
  extra-dep: true
- location:
    git: https://github.com/llelf/prose.git
    commit: ee32bef5cc7af41265ede92406943a5e2a60d530
  extra-dep: true
# reflex-platform:
- location:
    git: https://github.com/reflex-frp/reflex
    commit: 02cf9dbc89ba20b6e93622e0910a76d5e9d06669
  extra-dep: true
- location:
    git: https://github.com/ariep/ghcjs-websockets-reflex.git
    commit: 1d3b149db0e22496b2549bf10dfa503a3a1c2ee4
  extra-dep: true
# reflex-platform:
- location:
    git: https://github.com/reflex-frp/reflex-dom
    commit: 59100d61282fe02aa39be602f0a73daf31e28f63
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex-dom-contrib.git
    # master:
    commit: 3a0a9bb3eeea330f6c20756dec09a43410395218
  extra-dep: true

extra-deps:
  - cereal-text-0.1.0.2
  # for prose
  - data-list-sequences-0.1
  - ghcjs-dom-0.2.4.0
  - prim-uniq-0.1.0.1
  - ref-tf-0.4.0.1
  - string-conv-0.1.1
  - jsaddle-0.8.3.1
  - unicode-properties-3.2.0.0
  - zenc-0.1.1
