resolver: lts-7.19

packages:
- common
- server
- location:
    git: https://github.com/ariep/plug.git
    commit: cb36911068d162e7afa05d038847524ddae90e9e
  subdirs:
    - plug-common
    - plug-server
  extra-dep: true
- location:
    git: https://github.com/ariep/Coroutine.git
    commit: 19939a1bf73af951e06931fd29eacd45f5761ca8
  extra-dep: true
- location:
    git: https://github.com/ariep/TCache.git
    commit: 21c336e8bd992a5cdc64f48aa41d94d4a775b4b8
  extra-dep: true
- location:
    git: https://github.com/ariep/ID.git
    commit: 489623f74274dd360519726ea3358a65f5dfa811
  extra-dep: true
- location:
    git: https://github.com/ariep/text-index.git
    commit: 8f4453c088a786af89ef4a6079476d58add9b1ed
  extra-dep: true
- location:
    git: https://github.com/llelf/prose.git
    commit: ee32bef5cc7af41265ede92406943a5e2a60d530
  extra-dep: true
- location:
    git: https://github.com/ariep/oauth2-google.git
    commit: a855fed4104e17212b0ebfe71123d57366458b9e
  extra-dep: true
- location:
    git: https://github.com/ariep/language-spelling.git
    commit: 98936c01f0fc0baf35b24e9ae975a5d808123aa3
  subdirs: [tst]
  extra-dep: true
- location:
    git: https://github.com/ariep/psqueues.git
    commit: 1b9d87511bce9f5a3e4db6fa46a43dc03a965308
  extra-dep: true
- location:
    git: https://github.com/ariep/configifier.git
    commit: bec1aaf18abcca1a012c09d6e9cc8679a40faa36
  extra-dep: true

extra-deps:
  - console-program-0.4.2.1
  - data-list-sequences-0.1
  - functor-infix-0.0.5
  - http-accept-0.2
  - parsec-extra-0.2.0.0
  - unicode-properties-3.2.0.0
  - wai-util-0.8
